### ISSUE TITLE
Transfer this project

### ISSUE THREAD

**Issue by rpatterson** [rpatterson/github-apt-repos#6]
I'm no longer using this project and don't have time to maintain it.  I'm happy to hand this off to anyone using it for maintenance and/or further development.

**Comment by rpatterson** [comment]
Moving the discussion with @kylehuff from [another issue](https://github.com/rpatterson/github-apt-repos/pull/2#issuecomment-1730023394) here.

> @rpatterson I'd be happy to maintain this since I am actively using it in a few projects for work.

Sold!  I've never handed a project off to someone else on GitHub before, what's the best way to do that?  I've invited you as a "collaborator" under the repo's settings.  Is it better for you to fork the repository and I can add a note to the `./README.rst` here?  Something else?  LMK what you need.

**Comment by rpatterson** [comment]
For posterity, I started using this approach and created this project because some previously open source projects I was using started incrementally locking down and eventually went closed source.  During those transitions, they stopped publishing packages to any APT repository so I used this approach to keep my installs up to date.  Since then, community maintainers of those projects forked them from before going closed source and resumed releasing to APT repositories so I stopped needing this.

Since that time, CD platforms have matured a lot so I wonder if there isn't some better, but still free, way to publish to such APT repositories from GitHub these days.  Just a thought.

**Comment by kylehuff** [comment]
> Sold! I've never handed a project off to someone else on GitHub before, what's the best way to do that? I've invited you as a "collaborator" under the repo's settings. Is it better for you to fork the repository and I can add a note to the `./README.rst` here? Something else? LMK what you need.

Either way is fine with me, though continuing the project with the current watchers/stars would probably be best. But however you decide is fine. If transferring ownership is the route you want to take, that can be done in the repo settings at the bottom (in the "danger zone")

**Comment by rpatterson** [comment]
> though continuing the project with the current watchers/stars would probably be best.

Lets call that the winning argument.  I see you accepted the collaborator argument, so I think we're good to go.  LMK if you need anything else and thanks much for keeping this alive!

**Comment by kylehuff** [comment]
Great, thanks for you original efforts on this! It's made my life easier host our company debs internally. I mostly use the `--apt-dir` option, but I have started using it for git-hub too.

I'll get to work with the pull-requests.

P.S. If you get tired of this repo making noise, feel free to transfer ownership to me. That should retain forks/watchers/stars, it will also redirect the URL so long as the original owner doesn't create or fork a repo of the same name. The only thing I am aware of that will get lost in a transfer of ownership is github-pages, if present.

**Comment by rpatterson** [comment]
> Great, thanks for you original efforts on this! It's made my life easier host our company debs internally.

Wow, it's rare and very rewarding to have one of my one-off personal projects get real use by others.  Thanks!

> P.S. If you get tired of this repo making noise, feel free to transfer ownership to me.

Actually I like keeping tabs and I don't mind the credit.  ;-)  But if you ever come to prefer I transfer the project I'm happy to do so, just LMK.
